#!/usr/bin/env perl

package
    perlachievements;


use strict;
use warnings;

use Getopt::Long;


GetOptions( \my %arg,
    'run!',
    'list!',
);

use Perl::Achievements;

my $app = Perl::Achievements->new;

exit $app->list_achievements if $arg{list};

if ( $arg{run} ) {
    $app->run( @ARGV );
}
else {
    $app->peruse( @ARGV );
}



=pod

=head1 NAME

perlachievements

=head1 VERSION

version 0.0.1

=head1 NAME

perl-achievements - run some perl, collect some badges

=head2 OPTIONS

=over

=item --run

Runs the program after analyzing it.

=item --list

Lists all achievements unlocked so far.

=back

=head1 AUTHOR

  Yanick Champoux <yanick@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2010 by Yanick Champoux.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut


__END__
