#!/usr/bin/env perl

package
    perlachievements;

use Perl::Achievements;

Perl::Achievements->run;

exit;


use strict;
use warnings;

use Getopt::Long;

=head1 NAME

perl-achievements - run some perl, collect some badges

